import type { Taxonomy, Task, Run } from '@/types'

// These imports resolve to JSON files generated by prepare-data.ts
import taxonomyJson from './taxonomy.json'
import tasksJson from './tasks.json'
import runsJson from './runs.json'

export const taxonomy: Taxonomy = taxonomyJson as Taxonomy
export const tasks: Task[] = tasksJson as Task[]
export const runs: Run[] = runsJson as Run[]

export function getTask(elementId: string): Task | undefined {
  return tasks.find(t => t.element_id === elementId)
}

export function getRun(runId: string): Run | undefined {
  return runs.find(r => r.summary.run_id === runId)
}

export function getTaxonomyElement(id: string) {
  return taxonomy.elements.find(e => e.id === id)
}

export function getTaxonomyCategory(id: string) {
  return taxonomy.categories.find(c => c.id === id)
}
